// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nobuenhombre/go-draft/src/cmd/go-draft/di/providers/configs"
	"github.com/nobuenhombre/go-draft/src/cmd/go-draft/di/providers/domain"
	"github.com/nobuenhombre/go-draft/src/cmd/go-draft/di/providers/infrastructure"
	"github.com/nobuenhombre/go-draft/src/internal/app/go-draft/domain"
)

// Injectors from wire.go:

func InitializeApp() (domainapp.DomainService, func(), error) {
	service, cleanup, err := configs.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	dirsService, cleanup2, err := infrastructure.ProvideDirsService()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	varsService, cleanup3, err := infrastructure.ProvideVarsService()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	domainService, cleanup4, err := domain.ProvideDomain(service, dirsService, varsService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return domainService, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
