// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nobuenhombre/go-draft/src/internal/app/go-draft/cli"
	"github.com/nobuenhombre/go-draft/src/internal/app/go-draft/domain"
	"github.com/nobuenhombre/go-draft/src/internal/pkg/services/dirs"
	"github.com/nobuenhombre/go-draft/src/internal/pkg/services/vars"
)

// Injectors from wire.go:

// initializeApp is the Wire injector entrypoint. It aggregates all ProviderSets
// and constructs the top-level application. No logic belongs here.
func initializeApp() (IApp, func(), error) {
	service, cleanup, err := cli.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	dirsService, cleanup2, err := dirs.ProvideDirsService()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	varsService, cleanup3, err := vars.ProvideVarsService()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	domainService, cleanup4, err := domainapp.ProvideDomain(service, dirsService, varsService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iApp, cleanup5, err := newApp(domainService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return iApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
